### PR TITLE
Support Docker

### PR DESCRIPTION
**Pull request by wolveix**
Hey! Great repo, thanks for your hard work!

I wanted to add Docker support to make it even simpler for many people to deploy this :) 

I also simplified your SQL schema file a little bit (no schema changes, just simplified queries).

Let me know what you think! I'd be happy to make any changes you need :)

### CODE REVIEW

**Comment by wolveix** [comment]
As a note, you don't need to worry about manually building the Docker image yourself, GitHub will do it for you (for free) per the GitHub Action workflow I've provided, too!

**Comment by ciccionamente** [comment]
Hey @wolveix, thank you so much for your message and for your contribution, I really appreciate that! I'll merge the pull request but first I would like to ask if I can add you in the credits section of the readme file - would that sound good for you?

**Comment by wolveix** [comment]
@ciccionamente you're so welcome! Yes absolutely, that'd be fine :)

**Comment by ciccionamente** [comment]
@wolveix thank you, I just merged! 

I'm currently getting the following error on push: 

`The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/`

Any idea?

**Comment by wolveix** [comment]
@ciccionamente huh, try changing the following:
`- uses: actions/checkout@v2`

To:
`- uses: actions/checkout@main`

In `.github/workflows/docker.yml`

**Comment by wolveix** [comment]
I see there's the following error in the run, I haven't seen this before:
```
denied: installation not allowed to Create organization package
```

Might be a repo setting, researching it. Apologies for the hassle @ciccionamente!

**Comment by wolveix** [comment]
@ciccionamente try changing:
```
runs-on: ubuntu-latest
```

To:
```
runs-on: ubuntu-latest
permissions:
  contents: read
  packages: write
```

**Comment by ciccionamente** [comment]
@wolveix no problem at all, thank you so much for quick responses. It works all fine now, warning and error disappeared! 🙂

**Pull request merged**
